version: "3.8"

services:
  start_container:
    image: zeeguu_extension
    stdin_open: true # docker run -i
    entrypoint: "bash"
    volumes:
      - .:/Zeeguu-extension
  
  build_chrome:
    image: zeeguu_extension
    entrypoint: "npm run buildZipChrome"
    volumes:
      - .:/Zeeguu-extension
  
  build_firefox:
    image: zeeguu_extension
    entrypoint: "npm run buildZipFirefox"
    volumes:
      - .:/Zeeguu-extension